# Analysis DAG Pipeline
# Run with: op pipeline --config analysis_single.yaml
# Dry run:  op pipeline --config analysis_single.yaml --dry-run

pipeline:
  name: "Analysis DAG Demo"
  steps:
    # Level 1: independent artifact generation (parallelizable)
    - name: index_bc1
      command: index
    - name: index_bc2
      command: index
    - name: pack_reads
      command: pack

    # Level 2: count only after indexes and pack are available
    - name: count_combinatorial
      command: xcount
      after: [index_bc1, index_bc2, pack_reads]

# Build BC1 index
index_bc1:
  barcode_data: "../analysis-pipeline/ribozyme_architecture.csv"
  barcode_column: "BC1"
  barcode_prefix_column: "OrangeForwardPrimer"
  barcode_suffix_column: null
  barcode_prefix_gap: 0
  barcode_suffix_gap: 0
  index_file: "a1_bc1"

# Build BC2 index with associate mapping
index_bc2:
  barcode_data: "../analysis-pipeline/ribozyme_architecture.csv"
  barcode_column: "BC2"
  barcode_prefix_column: "PinkForwardPrimer"
  barcode_suffix_column: "YellowReversePrimer"
  barcode_prefix_gap: 0
  barcode_suffix_gap: 0
  associate_data: "../analysis-pipeline/ribozyme_architecture.csv"
  associate_column: "Variant"
  associate_prefix_column: null
  associate_suffix_column: "PinkForwardPrimer"
  associate_prefix_gap: 0
  associate_suffix_gap: 0
  index_file: "a1_bc2"

# Pack paired-end reads
pack_reads:
  r1_fastq_file: "../analysis-pipeline/ribozyme_1M_R1.fq.gz"
  r2_fastq_file: "../analysis-pipeline/ribozyme_1M_R2.fq.gz"
  r1_read_type: forward
  r2_read_type: reverse
  minimum_r1_read_quality: 30
  minimum_r2_read_quality: 30
  minimum_r1_read_length: 10
  minimum_r2_read_length: 10
  pack_type: merge
  pack_size: 0.1
  pack_file: "a1_reads"

# Count barcode combinations
count_combinatorial:
  index_files: ["a1_bc1", "a1_bc2"]
  pack_file: "a1_reads"
  count_file: "a1_counts"
  mapping_type: sensitive
  barcode_errors: -1
  callback: null
  core_count: 0
  memory_limit: 0.0
  failed_reads_file: "a1_failedreads"
  failed_reads_sample_size: 1000
