# Parallel Pipeline Example
# Demonstrates DAG execution with parallel steps
# Run with: op pipeline --config parallel_pipeline.yaml
# Dry run:  op pipeline --config parallel_pipeline.yaml --dry-run

pipeline:
  name: "Parallel Design Demo"
  steps:
    # Level 1: These two run in parallel (no dependencies)
    - name: fwd_primer
      command: primer
    - name: barcode_design
      command: barcode

    # Level 2: Runs after fwd_primer completes
    - name: add_spacer
      command: spacer
      after: [fwd_primer]

    # Level 3: Runs after both barcode_design and add_spacer complete
    - name: finalize
      command: final
      after: [barcode_design, add_spacer]

# Forward primer design (runs at level 1)
fwd_primer:
  input_data: "variants.csv"
  output_file: "p1_fwd_primer.oligopool.primer.csv"
  oligo_length_limit: 150
  primer_sequence_constraint: "NNNNNNNNNNNNNNNNNNNN"
  primer_type: forward
  primer_column: "FwdPrimer"
  minimum_melting_temperature: 52
  maximum_melting_temperature: 58
  maximum_repeat_length: 8
  right_context_column: "Promoter"
  random_seed: 1

# Barcode design (runs at level 1, parallel with fwd_primer)
barcode_design:
  input_data: "variants.csv"
  output_file: "p1_barcode.oligopool.barcode.csv"
  oligo_length_limit: 150
  barcode_length: 10
  minimum_hamming_distance: 3
  maximum_repeat_length: 8
  barcode_column: "Barcode"
  barcode_type: terminus
  left_context_column: "Promoter"
  random_seed: 2

# Spacer design (runs at level 2, after fwd_primer)
add_spacer:
  input_data: "p1_fwd_primer.oligopool.primer.csv"
  output_file: "p2_spacer.oligopool.spacer.csv"
  oligo_length_limit: 150
  maximum_repeat_length: 8
  spacer_column: "Spacer"
  left_context_column: "FwdPrimer"
  random_seed: 3

# Finalize (runs at level 3, after barcode_design and add_spacer)
# Note: This example uses add_spacer output; in a real workflow you might
# merge outputs from parallel branches before finalizing
finalize:
  input_data: "p2_spacer.oligopool.spacer.csv"
  output_file: "p3_final.oligopool.final.csv"
